# Dependencies

highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Mark Innes
tagline:          'Digital expert'
description:      'Digital marketing expert from Aberdeen'
url:              http://markinnes.co.uk
baseurl:          '/'
paginate:         5
gems:             
                - jekyll-sitemap
                - jekyll-paginate

author:
  name:           'Mark Innes'
  url:            https://twitter.com/innesm4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/innesm4/innesm4.github.io